# More examples of Codefresh YAML can be found at
# https://codefresh.io/docs/docs/yaml-examples/examples/

version: "1.0"
# Stages can help you organize your steps in stages
stages:
  - "prepare"
  - "preview"
  - "verify"

steps:
  clone:
    title: "Cloning repository"
    type: "git-clone"
    repo: "aperture-sci/terraform-vcluster"
    # CF_BRANCH value is auto set when pipeline is triggered
    # Learn more at codefresh.io/docs/docs/codefresh-yaml/variables/
    revision: "${{CF_BRANCH}}"
    git: "github"
    stage: "prepare"


  ChooseCluster:
    image: codefresh/kubectl
    title: Choosing cluster
    working_directory: "${{clone}}" 
    stage: prepare
    commands:
      - kubectl config use-context kubecon-dev

  PreviewWithTerraform:
    image: hashicorp/terraform:1.3.7
    title: Terraform Plan
    working_directory: "${{clone}}" 
    stage: preview
    commands:
      - cp -r /codefresh/volume/sensitive/.kube/ ~/.kube 
      - terraform init
      - terraform plan






